(() => {
  'use strict';
  const $=s=>document.querySelector(s), base='/hotpoor/director/api';
  const originalFetch=window.fetch.bind(window);
  window.fetch=(input,options={})=>{
    const url=new URL(typeof input==='string'?input:input.url,location.href),project=window.directorStudio?.currentProject();
    if(window.directorCloud&&project&&url.origin===location.origin&&url.pathname.startsWith(base+'/')&&!/^\/(settings|models|collaboration)(\/|$)/.test(url.pathname.slice(base.length))&&url.pathname!==base+'/projects'){
      const headers=new Headers(options.headers||input.headers);headers.set('X-Director-Project',project.block_id);options={...options,headers};
    }
    if(window.directorPublicShare&&url.origin===location.origin&&url.pathname.startsWith(base+'/')){const headers=new Headers(options.headers||input.headers);headers.set('X-Director-Share',window.directorPublicShare);options={...options,headers};}
    return originalFetch(input,options);
  };
  const labels={owner:'所有者',admin:'管理员',editor:'可编辑',commenter:'可评论',viewer:'只读'};
  const text=(tag,value)=>{const e=document.createElement(tag);e.textContent=value;return e;};
  async function api(path,body){const response=await fetch(base+'/collaboration/'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.detail||result.error||'操作失败');return result;}
  const dialog=document.createElement('dialog');dialog.id='collaboration-dialog';dialog.innerHTML=`<div class="dialog-heading"><h2>分享与成员</h2><button class="quiet" id="collaboration-close">✕</button></div><p id="collaboration-role"></p><p>成员生成时使用自己的模型 AK，费用归各自账号；新增媒体使用发起人的云存储配置。查看、评论和编辑画布不要求模型 AK。</p><div class="sync-actions"><button id="collaboration-my-models" class="quiet">我的模型 AK</button><button id="collaboration-my-storage" class="quiet">我的云存储</button></div><section id="collaboration-manage"><h3>邀请成员</h3><form id="collaboration-invite"><label>已注册并验证的邮箱<input name="login" type="email" required></label><label>权限<select name="role"><option value="viewer">只读</option><option value="commenter">可评论</option><option value="editor">可编辑</option><option value="admin">管理员</option></select></label><label><input name="can_generate" type="checkbox">允许使用其自己的 AK 发起生成（仅编辑 / 管理员）</label><button>添加 / 更新成员</button></form><div id="collaboration-members"></div><h3>只读分享链接</h3><p>未登录也可打开链接观看，访客不能评论。登录后的评论仍需成员评论权限。撤销或到期会收回通过该链接获得的访问权。</p><form id="collaboration-link"><label>链接名称<input name="label" required maxlength="80" placeholder="例如 客户审阅"></label><label>有效期<select name="duration" required><option value="">请选择</option><option value="7">7 天</option><option value="30">30 天</option><option value="custom">自定义日期</option><option value="never">永不过期</option></select></label><label id="collaboration-date" hidden>到期日期<input name="date" type="date"></label><button>创建只读链接</button></form><p id="collaboration-new-link"></p><div id="collaboration-links"></div></section><p id="collaboration-message" role="status"></p>`;
  $('#studio').append(dialog);$('#collaboration-close').onclick=()=>dialog.close();$('#collaboration-my-models').onclick=()=>{dialog.close();$('#open-inference-settings').click();};$('#collaboration-my-storage').onclick=()=>{dialog.close();$('#open-storage-settings').click();};
  const button=text('button','分享与成员');button.className='quiet';button.id='share-project';button.hidden=true;$('#edit-project').after(button);let projectId;
  async function load(){const project=window.directorStudio.currentProject();if(!project)throw Error('请先打开项目');projectId=project.block_id;const p=await api(projectId);$('#collaboration-role').textContent='你的权限：'+labels[p.role]+(p.can_generate?' · 可使用自己的 AK 生成':'');$('#collaboration-manage').hidden=!['owner','admin'].includes(p.role);if($('#collaboration-manage').hidden)return;
    const members=await api(projectId+'/members');$('#collaboration-members').replaceChildren(...members.members.map(m=>{const row=text('p',m.login+' · '+labels[m.role]+(m.can_generate?' · 允许生成':''));const remove=text('button','移除');remove.className='quiet';remove.onclick=()=>work(async()=>{await api(projectId+'/members/'+m.user_id,{});await load();});row.append(remove);return row;}));
    const links=await api(projectId+'/links');$('#collaboration-links').replaceChildren(...links.links.map(l=>{const row=text('p',l.label+' · '+(l.revoked_at?'已撤销':l.expires_at===null?'永不过期':new Date(l.expires_at).toLocaleString()));if(!l.revoked_at){const revoke=text('button','撤销');revoke.className='quiet';revoke.onclick=()=>work(async()=>{await api(projectId+'/links/'+l.id,{});await load();});row.append(revoke);}return row;}));
  }
  let busy=false;async function work(fn){if(busy)return;busy=true;$('#collaboration-message').textContent='正在处理…';try{await fn();$('#collaboration-message').textContent='已完成';}catch(e){$('#collaboration-message').textContent=e.message;}finally{busy=false;}}
  button.onclick=()=>{dialog.showModal();work(load);};
  $('#collaboration-invite').onsubmit=e=>{e.preventDefault();const f=e.target;work(async()=>{await api(projectId+'/members',{login:f.elements.login.value,role:f.elements.role.value,can_generate:f.elements.can_generate.checked});await load();});};
  $('#collaboration-link').elements.duration.onchange=e=>{$('#collaboration-date').hidden=e.target.value!=='custom';$('#collaboration-link').elements.date.required=e.target.value==='custom';};
  $('#collaboration-link').onsubmit=e=>{e.preventDefault();const f=e.target;work(async()=>{const duration=f.elements.duration.value;const expires=duration==='never'?null:duration==='custom'?new Date(f.elements.date.value+'T23:59:59.999').getTime():Date.now()+Number(duration)*86400000;const r=await api(projectId+'/links',{label:f.elements.label.value,expires_at:expires});const link=text('a','打开只读分享链接');link.href=location.origin+'/hotpoor/director?share='+encodeURIComponent(r.token);const copy=text('button','复制链接');copy.className='quiet';copy.onclick=()=>work(async()=>{await navigator.clipboard.writeText(link.href);});$('#collaboration-new-link').replaceChildren(link,copy);await load();});};
  function permissions(){if(!window.directorCloud)return;button.hidden=!!window.directorPublicShare;const project=window.directorStudio.currentProject(),p=project?.permission;const edit=!p||['owner','editor','admin'].includes(p.role),comment=edit||p?.role==='commenter',generate=edit&&(!p||p.can_generate);
    $('#studio').classList.toggle('project-readonly',!edit);
    for(const id of ['edit-project','add-assets','add-image','add-video','add-chat'])$('#'+id).disabled=!edit;
    document.querySelectorAll('.generation-card input,.generation-card select,.generation-card textarea,.remove-card,.chat-save-settings').forEach(e=>{if(!edit)e.disabled=true;});
    document.querySelectorAll('.generate').forEach(e=>{if(!generate)e.disabled=true;});
    document.querySelectorAll('.chat-composer input,.chat-composer select,.chat-composer textarea,.chat-composer button').forEach(e=>{if(!comment)e.disabled=true;});
    document.querySelectorAll('.chat-rich').forEach(e=>e.contentEditable=String(comment));
  }
  new MutationObserver(permissions).observe($('#canvas-world'),{childList:true,subtree:true});
  window.addEventListener('director-project-opened',permissions);
  window.addEventListener('director-cloud-ready',()=>{permissions();if(window.directorPublicShare)return;const token=new URLSearchParams(location.search).get('share');if(!token)return;const join=document.createElement('dialog');join.id='collaboration-join';join.innerHTML='<h2>加入只读项目</h2><p>使用当前账号查看分享的项目，不会获得项目所有者的密钥。</p>';const accept=text('button','加入并打开'),close=text('button','暂不加入'),notice=text('p','');close.className='quiet';close.onclick=()=>join.close();accept.onclick=async()=>{accept.disabled=true;try{const r=await api('join',{token});history.replaceState(null,'','/hotpoor/director');join.close();await window.directorStudio.openProject(r.project_id);}catch(e){notice.textContent=e.message;accept.disabled=false;}};join.append(accept,close,notice);$('#studio').append(join);join.showModal();});
})();
