(() => {
  'use strict';
  const $=s=>document.querySelector(s), state={targets:[],selected:'',preview:null,busy:false,auto:false,status:null,remoteDirty:new Set()};
  const time=n=>n?new Date(n).toLocaleString('zh-CN',{hour12:false})+' ('+n+' ms)':'尚无记录';
  const text=(tag,value,cls)=>{const e=document.createElement(tag);e.textContent=value;if(cls)e.className=cls;return e;};
  async function api(path,body){const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-XSRFToken':decodeURIComponent(document.cookie.split('; ').find(x=>x.startsWith('_xsrf='))?.slice(6)||'')},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();if(!r.ok){const e=Error(d.error||d.detail||'请求失败');e.status=r.status;throw e;}return d;}
  const dialog=document.createElement('dialog');dialog.id='sync-dialog';
  dialog.innerHTML=`<div class="dialog-heading"><h2>同步云端 · 版本与差异</h2><button id="sync-close" class="quiet">✕</button></div><p>保留双方版本。拉回本地时创建新 UUID，并自动向云端回传接收记录。</p><div class="sync-layout"><aside><h3>我的云端</h3><div id="sync-target-list"></div><button id="sync-add" class="quiet">＋ 添加云端</button><form id="sync-target-form"><label>名称<input name="name" maxlength="80" required></label><label>域名和产品路径<input name="url" type="url" placeholder="https://api.xialiwei.com/hotpoor/director" required></label><label>Access Key<input name="access_key" type="password" autocomplete="off" placeholder="可留空，保存后登录云端授权"></label><button>保存配置</button><button type="button" id="sync-remove" class="quiet">移除此配置</button></form><button id="sync-authorize">登录云端并授权</button><p id="sync-auth-note"></p><a id="sync-auth-link" target="_blank" rel="noopener noreferrer" hidden>打开云端授权页面</a></aside><section><h3 id="sync-project-name">当前项目</h3><label><input id="sync-enabled" type="checkbox">开启此项目对此云端的同步标识和自动同步</label><p>自动同步只提交云端没有新改动的版本；发现差异时暂停，并保留双方内容。</p><div class="sync-actions"><button id="sync-preview">比较差异</button><button id="sync-push" disabled>提交本地版本</button><button id="sync-pull" disabled>拉回新副本并回传</button><button id="sync-receipt" class="quiet">重试回传记录</button></div><label><input id="sync-keep-both" type="checkbox">双方有修改时，保留云端旧项目并提交本地为新版本</label><p id="sync-summary" role="status"></p><div id="sync-diff"></div><button id="sync-export-diff" class="quiet" disabled>导出完整差异 JSON</button><h3>云端项目</h3><button id="sync-catalog" class="quiet">读取云端项目列表</button><div id="sync-cloud-projects"></div></section></div><p id="sync-message" role="status"></p>`;
  $('#studio').append(dialog);
  const openButton=text('button','同步云端','quiet');openButton.dataset.desktopSync='';$('.studio-nav').insertBefore(openButton,$('#studio-logout'));
  const historyButton=text('button','修改历史','quiet');$('.canvas-bottom').prepend(historyButton);
  const history=document.createElement('dialog');history.id='sync-history';history.innerHTML='<div class="dialog-heading"><h2>修改历史 · 持久保存的操作</h2><button id="history-close" class="quiet">✕</button></div><p>按服务端记录时间排列。每次保存保留修改前后内容，时间用于查阅，不用于静默覆盖。</p><div id="history-events"></div>';
  $('#studio').append(history);$('#history-close').onclick=()=>history.close();
  function project(){return window.directorStudio.currentProject();}
  function route(){if(!project())throw Error('请先打开本地项目');if(!state.selected)throw Error('请选择云端');return '/api/sync/projects/'+project().block_id+'/targets/'+state.selected;}
  async function work(fn){if(state.busy)return;state.busy=true;$('#sync-message').textContent='正在处理…';dialog.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();$('#sync-message').textContent='操作完成';}catch(e){$('#sync-message').textContent=e.message;}finally{state.busy=false;dialog.querySelectorAll('button').forEach(b=>b.disabled=false);updateActions();}}
  function updateActions(){const ready=!!state.preview&&!!project();$('#sync-push').disabled=!ready||state.busy;$('#sync-pull').disabled=!ready||!state.preview.remote_hash||state.busy;$('#sync-export-diff').disabled=!state.preview;$('#sync-project-name').textContent=project()?.body.title||'先打开本地项目，或从下方拉回云端项目';}
  function choose(id){state.selected=id;state.preview=null;const t=state.targets.find(t=>t.id===id);const f=$('#sync-target-form');f.elements.name.value=t?.name||'';f.elements.url.value=t?.url||'https://api.xialiwei.com/hotpoor/director';f.elements.access_key.value='';$('#sync-auth-note').textContent=t?.authorized?'已保存授权；密钥不回显':'尚未授权';$('#sync-auth-link').hidden=true;renderTargets();updateActions();refreshStatus();}
  function renderTargets(){$('#sync-target-list').replaceChildren(...state.targets.map(t=>{const b=text('button',t.name+(t.authorized?' · 已授权':' · 待授权'),t.id===state.selected?'':'quiet');b.onclick=()=>{if(!state.busy)choose(t.id);};return b;}));}
  async function load(){state.targets=(await api('/api/sync/targets')).targets;choose(state.selected||state.targets[0]?.id||'');}
  openButton.onclick=()=>{dialog.showModal();work(load);};$('#sync-close').onclick=()=>{if(!state.busy)dialog.close();};$('#sync-add').onclick=()=>choose('');
  $('#sync-target-form').onsubmit=e=>{e.preventDefault();const f=e.target;work(async()=>{const old=new Set(state.targets.map(x=>x.id));state.targets=(await api('/api/sync/targets',{id:state.selected||undefined,...Object.fromEntries(new FormData(f))})).targets;choose(state.selected||state.targets.find(t=>!old.has(t.id))?.id||'');});};
  $('#sync-remove').onclick=()=>work(async()=>{state.targets=(await api('/api/sync/targets',{id:state.selected,action:'remove'})).targets;choose(state.targets[0]?.id||'');});
  let authorizationTimer;
  $('#sync-authorize').onclick=()=>work(async()=>{if(!state.selected)throw Error('请先保存配置');const id=state.selected;const r=await api('/api/sync/targets/'+id+'/authorize',{});$('#sync-auth-note').textContent='核对授权码：'+r.user_code+'，十分钟内完成登录授权';const a=$('#sync-auth-link');a.href=r.verification_url;a.hidden=false;a.onclick=window.directorDesktop?e=>{e.preventDefault();window.directorDesktop.openAuthorization(r.verification_url);}:null;
    if(window.directorDesktop)await window.directorDesktop.openAuthorization(r.verification_url);else window.open(r.verification_url,'_blank','noopener');
    clearInterval(authorizationTimer);const until=Date.now()+r.expires_in*1000;authorizationTimer=setInterval(async()=>{if(Date.now()>until){clearInterval(authorizationTimer);$('#sync-auth-note').textContent='授权已过期，请重新发起';return;}try{const result=await api('/api/sync/targets/'+id+'/authorize',{action:'poll'});if(result.status==='authorized'){clearInterval(authorizationTimer);await load();$('#sync-auth-note').textContent='云端登录授权成功';}}catch(e){if(e.status!==429){clearInterval(authorizationTimer);$('#sync-auth-note').textContent=e.message;}}},Math.max(3,r.interval)*1000);
  });
  function showChanges(container,title,changes){const details=document.createElement('details');details.open=changes.length<12;details.append(text('summary',title+' · '+changes.length+' 项'));for(const c of changes.slice(0,200)){const row=text('div','', 'sync-change '+c.operation);row.append(text('code',c.path));if('before'in c)row.append(text('pre','− '+JSON.stringify(c.before,null,2)));if('after'in c)row.append(text('pre','＋ '+JSON.stringify(c.after,null,2)));details.append(row);}if(changes.length>200)details.append(text('p','页面先展示 200 项，可导出完整差异。'));container.append(details);}
  async function preview(){await window.directorStudio.save();state.preview=await api(route(),{action:'preview'});const d=state.preview;$('#sync-diff').replaceChildren();showChanges($('#sync-diff'),'本地相对共同版本',d.local_changes);showChanges($('#sync-diff'),'云端相对共同版本',d.remote_changes);$('#sync-summary').textContent=(d.identical?'两端内容一致':d.conflicts.length?'存在 '+d.conflicts.length+' 处冲突，双方内容保留':'可比较并选择要保留的版本')+' · 本地保存 '+time(d.local_time)+' · 云端修改 '+time(d.remote_time);updateActions();}
  $('#sync-preview').onclick=()=>work(preview);
  $('#sync-push').onclick=()=>work(async()=>{const r=await api(route(),{action:'push',local_hash:state.preview.local_hash,remote_hash:state.preview.remote_hash,resolution:$('#sync-keep-both').checked?'keep-both':undefined});$('#sync-summary').textContent='已提交 · 云端 UUID '+r.project_id+' · '+time(r.recorded_at);state.preview=null;await refreshStatus();});
  $('#sync-receipt').onclick=()=>work(async()=>{await api(route()+'/receipt',{});$('#sync-summary').textContent='接收记录已回传';await refreshStatus();});
  $('#sync-pull').onclick=()=>work(async()=>{const r=await api(route(),{action:'pull',remote_hash:state.preview.remote_hash});await window.directorStudio.openProject(r.project_id);state.preview=null;$('#sync-summary').textContent=r.note;await refreshStatus();});
  $('#sync-catalog').onclick=()=>work(async()=>{if(!state.selected)throw Error('请选择云端');const data=await api('/api/sync/targets/'+state.selected+'/catalog');$('#sync-cloud-projects').replaceChildren(...data.projects.map(p=>{const row=text('div','', 'sync-cloud-project');row.append(text('strong',p.title),text('small',time(p.updated_at)+' · '+p.project_id));const b=text('button','拉回新 UUID 副本','quiet');b.onclick=()=>work(async()=>{await window.directorStudio.save();const r=await api('/api/sync/targets/'+state.selected+'/catalog',{lineage:p.lineage});await window.directorStudio.openProject(r.project_id);state.preview=null;$('#sync-summary').textContent=r.pending_receipt?'新副本已保留；回传待重试':'已创建新副本并回传云端';await refreshStatus();});row.append(b);return row;}));});
  $('#sync-export-diff').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state.preview,null,2)],{type:'application/json'}));a.download='director-diff-'+Date.now()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000);};
  $('#sync-enabled').onchange=()=>work(async()=>{if(!project()||!state.selected)throw Error('请打开项目并选择云端');await api('/api/sync/projects/'+project().block_id+'/status',{target_id:state.selected,enabled:$('#sync-enabled').checked});await refreshStatus();});
  async function historyPage(projectId,cursor=''){const r=await api('/api/sync/projects/'+projectId+'/timeline'+(cursor?'?cursor='+encodeURIComponent(cursor):''));$('#history-more')?.remove();for(const e of r.events)showChanges($('#history-events'),time(e.at)+' · '+e.operation+' · '+e.entity_id,e.changes);if(r.next_cursor){const more=text('button','读取更早的修改','quiet');more.id='history-more';more.onclick=async()=>{more.disabled=true;try{await historyPage(projectId,r.next_cursor);}catch(e){more.disabled=false;more.textContent=e.message+' · 点击重试';}};$('#history-events').append(more);}}
  historyButton.onclick=async()=>{if(!project())return;history.showModal();$('#history-events').replaceChildren();try{await historyPage(project().block_id);}catch(e){$('#history-events').textContent=e.message;}};
  async function refreshStatus(){if(window.directorCloud||!project())return;const id=project().block_id;try{const s=await api('/api/sync/projects/'+id+'/status');if(project()?.block_id!==id)return;state.status=s;$('#sync-enabled').checked=!!s.targets.find(t=>t.id===state.selected)?.enabled;document.querySelectorAll('[data-card]').forEach(el=>{if(!el.classList.contains('generation-card')&&!el.classList.contains('asset-card')&&!el.classList.contains('chat-card'))return;el.querySelector(':scope > .sync-card-status')?.remove();const enabled=s.targets.filter(t=>t.enabled);if(!enabled.length)return;const badge=text('span',enabled.map(t=>t.name+'：'+(state.remoteDirty.has(id+':'+t.id)?'云端有新版本':(t.cards[el.dataset.card]||'待同步'))+(t.pending_receipt?' · 回传待重试':'')).join(' / '),'sync-card-status');badge.title=enabled.map(t=>t.name+' 最近同步 '+time(t.last_sync)).join('\n');el.append(badge);});}catch{}updateActions();}
  window.addEventListener('director-changed',()=>{state.preview=null;document.querySelectorAll('.sync-card-status').forEach(b=>b.textContent='有本地修改 · 待比较');});
  let statusTimer=setInterval(async()=>{
    if(!document.body.classList.contains('studio-active')||window.directorCloud)return;
    await refreshStatus();
    if(state.busy||!project()||!state.status)return;
    const projectId=project().block_id,targets=state.status.targets.filter(t=>t.enabled);
    for(const t of targets){
      if(state.busy||project()?.block_id!==projectId)break;
      state.busy=true;
      try{
        await window.directorStudio.save();
        if(project()?.block_id!==projectId)break;
        const r='/api/sync/projects/'+projectId+'/targets/'+t.id;
        if(t.pending_receipt)await api(r+'/receipt',{});
        const p=await api(r,{action:'preview'});
        if(p.remote_changes.length&&!p.identical){state.remoteDirty.add(projectId+':'+t.id);openButton.textContent='同步云端 · 有差异待处理';}
        else{state.remoteDirty.delete(projectId+':'+t.id);if(t.status==='待同步')await api(r,{action:'push',local_hash:p.local_hash,remote_hash:p.remote_hash});}
      }catch(e){openButton.textContent='同步云端 · '+e.message.slice(0,24);}
      finally{state.busy=false;}
    }
  },10000);
})();
